### ISSUE TITLE
不避风云，你好，我想请教一下yii2-tree-Manager的NodeController中的Manager和Save各是怎么工作的？怎么完成各种增（root节点/正常节点）、改、查的？谢谢

### ISSUE THREAD

**Issue by chenbuer** [bubifengyun/book-yii2-dev-process#4]

**Comment by bubifengyun** [comment]
当时把原来那个模块module移植到前台frontend的原因就是，不想直接修改vendor下的内容，以免后续升级的时候，所做工作报废了。

另外我不知道你的代码能否调试，如果不可以调试，给你推荐两个去处，第一是vscode,及对应的PHP调试插件，我试过，非常好用，vscode支持Linux，Windows和Mac。第二个是我的vim及对yii2的调试，不太建议使用，在我的这本书第一章好像就是写的这个玩意。另外如果你用的是火狐的话，还有firebug调试工具的。

下面假设你可以调试代码了，找到对应的manager函数，就可以写边运行边看了。

我主要是想让他一边是树形结构，一边是表格，所以只修改了他manager的内容，其他增删之类的操作保持不动。manager作为页面作为单独的内容，有自己的操作，不需要treemanager再参与了。

我不知道你是个啥想法，是仅仅使用树形结构，还是跟我一样的想法？

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/book-yii2-dev-process/blob/master/src/ch-18.md

这篇博客，哪里有不懂的，你可以写下来，我可以修改，写的更明了。谢谢。

**Comment by bubifengyun** [comment]
确实抱歉。后来我又对代码进行了修改，已经跟写作这篇博客的内容差别太多了。如果你需要源码的，我下次找个电脑可以联网的时候，先把一个示例代码发给你，你留个可以可以接收的邮箱吧。

**Comment by chenbuer** [comment]
@bubifengyun 谢谢啦，可以的话发一份到我的邮箱 chenzy08@126.com，我学习学习

**Comment by bubifengyun** [comment]
@chenbuer 源码已经发送，内容请参考休假相关的代码。

```
./frontend/
 views/personinfo/
   holiday.php
   _nodeholidaygridview.php
controllers/Personinfo.php
```

该代码尚未整理，最后统一开源，请不要随意传播源码，谢谢。
